version: "3"

volumes:
  evmapp-data:
  evmapp-snark-keys:
  zen-data:
  zcash-params:

networks:
  evmapp_network:
    internal: true
    ipam:
      config:
        - subnet: ${INTERNAL_NETWORK_SUBNET}
  inet:

services:
  zend:
    image: zencash/zen-node:${ZEN_TAG}
    container_name: zend
    restart: always
    networks:
      evmapp_network:
        ipv4_address: 10.10.50.10
      inet:
    ports:
      - "${ZEN_PORT}:${ZEN_PORT}"
    expose:
      - "${ZEN_RPC_PORT}"
      - "${ZEN_WS_PORT}"
    volumes:
      - "zen-data:/mnt/zen:rw"
      - "zcash-params:/mnt/zcash-params:rw"
      - "./scripts/seed.sh:/usr/local/bin/seed.sh:rw"
    environment:
      - "CUSTOM_SCRIPT=${ZEN_CUSTOM_SCRIPT}"
      - "EXTERNAL_IP=${ZEN_EXTERNAL_IP}"
      - "LOCAL_GRP_ID=${ZEN_LOCAL_GRP_ID}"
      - "LOCAL_USER_ID=${ZEN_LOCAL_USER_ID}"
      - "LOG=${ZEN_LOG}"
      - "OPTS=${ZEN_OPTS}"
      - "PORT=${ZEN_PORT}"
      - "RPC_ALLOWIP_PRESET=${ZEN_RPC_ALLOWIP_PRESET}"
      - "RPC_USER=${ZEN_RPC_USER}"
      - "RPC_PASSWORD=${ZEN_RPC_PASSWORD}"
      - "RPC_PORT=${ZEN_RPC_PORT}"
      - "SEED_TAR_GZ_URL=${ZEN_SEED_TAR_GZ_URL}"
    logging:
      driver: "json-file"
      options:
        max-size: "512m"
        max-file: "4"

  evmapp:
    image: zencash/evmapp:${SC_COMMITTISH_EVMAPP}
    container_name: evmapp
    depends_on:
      - zend
    restart: always
    networks:
      evmapp_network:
        ipv4_address: ${SCNODE_IP_ADDRESS}
      inet:
    expose:
      - "${SCNODE_REST_PORT}"
      - "${SCNODE_WS_SERVER_PORT}"
    ports:
      - "${SCNODE_NET_P2P_PORT}:${SCNODE_NET_P2P_PORT}"
    volumes:
      - "evmapp-data:/sidechain/datadir:rw"
      - "evmapp-snark-keys:/sidechain/snark_keys:rw"
      - "./logs/evmapp:/sidechain/logs:rw"
    environment:
      - "RPC_USER=${ZEN_RPC_USER}"
      - "RPC_PASSWORD=${ZEN_RPC_PASSWORD}"
      - "RPC_PORT=${ZEN_RPC_PORT}"
      - "LOCAL_GRP_ID=${SCNODE_GRP_ID}"
      - "LOCAL_USER_ID=${SCNODE_USER_ID}"
      - SCNODE_BACKUP_TAR_GZ_URL
      - SCNODE_CERT_SIGNERS_MAXPKS
      - SCNODE_CERT_SIGNERS_PUBKEYS
      - SCNODE_CERT_SIGNERS_SECRETS
      - SCNODE_CERT_SIGNERS_THRESHOLD
      - SCNODE_CERT_MASTERS_PUBKEYS
      - SCNODE_CERT_SIGNING_ENABLED
      - SCNODE_CERT_SUBMITTER_ENABLED
      - SCNODE_REMOTE_KEY_MANAGER_ENABLED
      - SCNODE_ALLOWED_FORGERS
      - SCNODE_FORGER_ENABLED
      - SCNODE_FORGER_RESTRICT
      - SCNODE_GENESIS_BLOCKHEX
      - SCNODE_GENESIS_SCID
      - SCNODE_GENESIS_POWDATA
      - SCNODE_GENESIS_MCBLOCKHEIGHT
      - SCNODE_GENESIS_MCNETWORK
      - SCNODE_GENESIS_WITHDRAWALEPOCHLENGTH
      - SCNODE_GENESIS_COMMTREEHASH
      - SCNODE_GENESIS_ISNONCEASING
      - SCNODE_NET_KNOWNPEERS
      - SCNODE_NET_MAGICBYTES
      - SCNODE_NET_MAX_IN_CONNECTIONS
      - SCNODE_NET_MAX_OUT_CONNECTIONS
      - SCNODE_NET_NODENAME
      - SCNODE_NET_P2P_PORT
      - SCNODE_NET_API_LIMITER_ENABLED
      - SCNODE_NET_SLOW_MODE
      - SCNODE_NET_REBROADCAST_TXS
      - SCNODE_NET_HANDLING_TXS
      - SCNODE_FORGER_MAXCONNECTIONS
      - SCNODE_ONLY_CONNECT_TO_KNOWN_PEERS
      - SCNODE_REST_PORT
      - SCNODE_WALLET_GENESIS_SECRETS
      - SCNODE_WALLET_MAXTX_FEE
      - SCNODE_WALLET_SEED
      - SCNODE_WS_ZEN_FQDN
      - "SCNODE_WS_ZEN_PORT=${ZEN_WS_PORT}"
      - SCNODE_WS_SERVER_PORT
      - SCNODE_WS_CLIENT_ENABLED
      - SCNODE_WS_SERVER_ENABLED
      - SCNODE_LOG_FILE_LEVEL
      - SCNODE_LOG_CONSOLE_LEVEL
    logging:
      driver: "json-file"
      options:
        max-size: "512m"
        max-file: "4"
